frame_extractor:
  CONFIDENCE_THRESHOLD: 0.6
  WAGON_CLASS_ID: 1
  CAPTURE_DELAY: 5
  MODEL_PATH: 'models/best_new.pt'
  TOP_MODEL_PATH: 'models/topbest.pt'
  CENTER_TOLERANCE_PX: 80
  TOP_MODEL_WAGON_ID: 0

app:
  port: 5005