version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis_service
    ports:
      - "6379:6379"
    # --- Caching Policy Implementation: Start ---
    # This command starts the Redis server and passes configuration flags.
    command: 
      - redis-server
      - --maxmemory 512mb
      - --maxmemory-policy volatile-lru
    # --- Caching Policy Implementation: End ---


  backend:
    build: .
    container_name: backend_service
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  cpu_worker:
    build: .
    container_name: cpu_worker_service
    # This worker ONLY consumes from the 'cpu_queue'
    command: ["celery", "-A", "services.celery_worker.celery", "worker", "-Q", "cpu_queue", "--loglevel=info"]
    volumes:
      - .:/app
    env_file: .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis